# Everything in this section will be available as an environment variable
public_gsheets_url = "https://docs.google.com/spreadsheets/d/1K4Akei7NW_kU1g2xZYqEkPZmig_ttMrsBo_Y0-oPcNw/edit#gid=0"

db_username = "Jane"
db_password = "12345qwerty"
 
[my_cool_secrets]
things_i_like = ["Streamlit", "Python"]
